eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: hello-service
---
spring:
  profiles: peer1
server:
  port: 10011
---
spring:
  profiles: peer2
server:
  port: 10012
---
spring:
  profiles: peer3
server:
  port: 10013
---
spring:
  profiles: peer4
server:
  port: 10014
---