---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: application1
  profiles: peer1
server:
  port: 10001
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: application1
  profiles: peer2
server:
  port: 10002
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: application1
  profiles: peer3
server:
  port: 10003
---