eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: zuul
server:
  port: 9031
zuul:
  routes:
    hi-service:
      path: /hi-service/**
      #url: http://localhost:10021/
      serviceId: hi-service
  decode-url: false
  #ignored-patterns: /hello-service/**
---
spring:
  profiles: peer1
server:
  port: 9031
---
spring:
  profiles: peer2
server:
  port: 9032
---
spring:
  profiles: peer3
server:
  port: 9033
---