---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: hi-service
  profiles: peer1
server:
  port: 10021
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: hi-service
  profiles: peer2
server:
  port: 10022
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: hi-service
  profiles: peer3
server:
  port: 10023
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: hi-service
  profiles: peer4
server:
  port: 10024
---